name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Set this to your default branch if different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Static Site
        run: make build  # Replace 'make build' with the actual command you use to build your site

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: static-files
          path: /path/to/output  # Replace '/path/to/output' with the path to your built static site files

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'  # Ensure this runs only on push to the default branch
        uses: actions/deploy-pages@v1

