name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Set this to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: List files
        run: ls -lha

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # This should point to the directory containing index.html, which in your case, is './'

